# Carpeta donde estan los fondos
preload = /home/ricardo/Wallpapers/Anime-City-Night.png

# Asigna fondo de pamtalla (hyprctl monitors)
wallpaper = eDP-1, /home/ricardo/Wallpapers/Anime-City-Night.png
