# Texto
foreground #f1eaff
selection_background #2a1f3d
selection_foreground #ffffff
font_family JetBrainsMono Nerd Font

# Cursor
cursor #ff4fd8
cursor_shape beam
cursor_blink_interval 0.6
scrollback_line 10000

# Fondo de la terminal
background #0b0b12
background_opacity 0.7
background_blur 1
window_padding_width 12

# Negro
color0 #15121c
color8 #4b3f5c

# Rojo / Rosa
color1 #ff4fd8
color9 #ff79e6

# Verde
color2 #00f5a0
color10 #5fffd7

# Amarilla
color3 #ffe066
color11 #fff3a3

# Azul
color4 #4da3ff
color12 #82c7ff

# Morado
color5 #b266ff
color13 #d1a6ff

# Cyan
color6 #00eaff
color14 #5ff6ff

# Blanco
color7 #d6d6ff
color15 #ffffff